name: bom_base_ui
description: BOM-Base client UI

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.11.0
  cupertino_icons: ^1.0.3
  material_floating_search_bar: ^0.3.4
  dio: ^4.0.0
  provider: ^5.0.0
  intl: ^0.17.0
  yeet: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5
  mockito: ^5.0.7
  build_runner: ^2.0.2

flutter:
  uses-material-design: true
