name: bom_base_ui
description: BOM-Base client UI

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  material_floating_search_bar: ^0.3.3
  dio: ^4.0.0
  provider: ^5.0.0
  intl: ^0.17.0

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  test: ^1.16.8
  mockito: ^5.0.3
  build_runner: ^1.12.2

flutter:

  uses-material-design: true
