name: Build application 

on:
  push:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_ORGANIZATION: philipssoftware
  GITHUB_ORGANIZATION: philips-software

jobs:
  build-and-test-frontend:
    name: Build frontend project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.5.0
        with:
          flutter-version: '2.2.0'

      - name: Install UI
        run: |
          cd ui
          ./install_ui

  
  build-and-test-backend:
    name: Build backend project
    runs-on: ubuntu-latest
    needs: build-and-test-frontend

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Cache build artifacts
        uses: actions/cache@v2.1.5
        with:
          path: |
            target/**/*.xml
            target/*.jar
          key: bom-base-${{ github.sha }}

      - uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'zulu'

      - name: Setup python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9' 

      - name: Install scancode 
        run: |
          pip install -r docker/requirements.txt
          scancode --version
          extractcode --version

      - name: Build with Maven
        run: mvn --no-transfer-progress install -DskipTests

      - name: Test with Maven
        run: mvn --no-transfer-progress test

  create-docker-image:
    name: "Create docker image"
    needs: build-and-test-backend

    runs-on: ubuntu-latest

    if: success()

    steps:
      - name: Checkout

        uses: actions/checkout@v2

      - name: Cache build artifacts
        uses: actions/cache@v2.1.5
        with:
          path: |
            target/**/*.xml
            target/*.jar
          key: bom-base-${{ github.sha }}

      - name: Build Docker Images
        uses: philips-software/docker-ci-scripts@v3.3.1
        with:
          dockerfile: docker/Dockerfile
          image-name: bom-base 
          tags: 0 0.1 0.1.0 v0.1.0 latest
